name: cipher-interceptor

services:
  backend:
    build:
      context: storage-backend
    volumes:
      - storage:/opt/storage
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "8080"]
      interval: 1s
      timeout: 1s
      retries: 5

  cipher:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: cipher-proxy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "nc", "-z", "0.0.0.0", "8080"]
      interval: 1s
      timeout: 1s
      retries: 5

  tests-e2e:
    depends_on:
      cipher:
        condition: service_healthy
    build:
      context: tests
    volumes:
      - storage:/opt/storage

volumes:
  storage:
